package no.nav.etterlatte.brev.brevbaker

enum class EtterlatteBrevKode(val tittel: String? = null) {
    BARNEPENSJON_AVSLAG,
    BARNEPENSJON_AVSLAG_UTFALL,
    BARNEPENSJON_INNVILGELSE,
    BARNEPENSJON_INNVILGELSE_UTFALL,
    BARNEPENSJON_OPPHOER,
    BARNEPENSJON_OPPHOER_UTFALL,
    BARNEPENSJON_REVURDERING,
    BARNEPENSJON_FORHAANDSVARSEL_OMREGNING,
    BARNEPENSJON_VEDTAK_OMREGNING,
    BARNEPENSJON_VEDTAK_OMREGNING_FERDIG,
    OMSTILLINGSSTOENAD_AVSLAG,
    OMSTILLINGSSTOENAD_AVSLAG_UTFALL,
    OMSTILLINGSSTOENAD_INNVILGELSE,
    OMSTILLINGSSTOENAD_INNVILGELSE_UTFALL,
    OMSTILLINGSSTOENAD_REVURDERING,
    OMSTILLINGSSTOENAD_REVURDERING_OPPHOER,
    OMSTILLINGSSTOENAD_REVURDERING_OPPHOER_UTFALL,
    OMSTILLINGSSTOENAD_REVURDERING_OPPHOER_MANUELL, // Denne bør fjernes
    TILBAKEKREVING_INNHOLD,
    TILBAKEKREVING_FERDIG,
    TOM_DELMAL,
    TOM_MAL_INFORMASJONSBREV,
    TOM_MAL,
    UTSATT_KLAGEFRIST("Informasjon om barnepensjon fra 1. januar 2024"),
}
