package no.nav.etterlatte.brev.brevbaker

enum class EtterlatteBrevKode(val tittel: String? = null) {
    BARNEPENSJON_AVSLAG("Vedtak om avslått barnepensjon"),
    BARNEPENSJON_AVSLAG_UTFALL,
    BARNEPENSJON_INNVILGELSE("Vedtak om innvilget barnepensjon"),
    BARNEPENSJON_INNVILGELSE_UTFALL,
    BARNEPENSJON_OPPHOER("Opphør av barnepensjon"),
    BARNEPENSJON_OPPHOER_UTFALL,
    BARNEPENSJON_REVURDERING,
    BARNEPENSJON_REVURDERING_UTFALL,
    BARNEPENSJON_FORHAANDSVARSEL_OMREGNING,
    BARNEPENSJON_VEDTAK_OMREGNING("Informasjon om omregning av barnepensjon"),
    BARNEPENSJON_VEDTAK_OMREGNING_FERDIG,
    OMSTILLINGSSTOENAD_AVSLAG("Vedtak om avslått omstillingsstønad"),
    OMSTILLINGSSTOENAD_AVSLAG_UTFALL,
    OMSTILLINGSSTOENAD_INNVILGELSE("Vedtak om innvilget omstillingsstønad"),
    OMSTILLINGSSTOENAD_INNVILGELSE_UTFALL,
    OMSTILLINGSSTOENAD_OPPHOER("Opphør av omstillingsstønad"),
    OMSTILLINGSSTOENAD_OPPHOER_UTFALL,
    OMSTILLINGSSTOENAD_REVURDERING,
    OMSTILLINGSSTOENAD_REVURDERING_OPPHOER_MANUELL, // Denne bør fjernes
    TILBAKEKREVING_INNHOLD,
    TILBAKEKREVING_FERDIG,
    TOM_DELMAL,
    TOM_MAL_INFORMASJONSBREV,
    TOM_MAL,
    UTSATT_KLAGEFRIST("Informasjon om barnepensjon fra 1. januar 2024"),
}
