version: 2

updates:
  # ==============
  # KOTLIN BACKEND
  # ==============
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 10
    groups:
      minor-and-patch-dependencies:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
      major-dependencies:
        patterns:
          - '*'
        update-types:
          - 'major'


  # =============
  # FRONTEND
  # =============
  - package-ecosystem: "npm"
    directories:
      - "/apps/etterlatte-saksbehandling-ui/client"
      - "/apps/etterlatte-saksbehandling-ui/server"
    schedule:
      interval: "weekly"
      day: "sunday"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 10
    groups:
      minor-and-patch-dependencies:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
      major-dependencies:
        patterns:
          - '*'
        update-types:
          - 'major'

  # ==============
  # GITHUB ACTIONS
  # ==============
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    cooldown:
      default-days: 7
    groups:
      github-actions:
        patterns:
          - "*"

  # ==============
  # Docker
  # ==============
  - package-ecosystem: "docker"
    directories:
      - /docker
      - /apps/etterlatte-saksbehandling-ui
    schedule:
      interval: "weekly"
      day: "sunday"
    cooldown:
      default-days: 7
    groups:
      dockerfilene:
        patterns:
          - "*"
