package no.nav.etterlatte.libs.common.vilkaarsvurdering

enum class VilkaarType {
    FORMAAL,
    FORUTGAAENDE_MEDLEMSKAP,
    FORUTGAAENDE_MEDLEMSKAP_UNNTAK_AVDOED_IKKE_FYLT_26_AAR,
    FORUTGAAENDE_MEDLEMSKAP_UNNTAK_AVDOED_MEDLEM_ETTER_16_AAR,
    FORUTGAAENDE_MEDLEMSKAP_UNNTAK_AVDOED_HALV_MINSTEPENSJON,
    FORUTGAAENDE_MEDLEMSKAP_UNNTAK_AVDOED_AVTALEFESTET_PENSJON,
    FORUTGAAENDE_MEDLEMSKAP_UNNTAK_AVDOED_LOVFESTET_PENSJONSORDNING,
    FORTSATT_MEDLEMSKAP,
    FORTSATT_MEDLEMSKAP_UNNTAK_FORELDRE_MINST_20_AAR_SAMLET_BOTID,
    FORTSATT_MEDLEMSKAP_UNNTAK_AVDOED_MINDRE_20_AAR_BOTID_RETT_TILLEGGSPENSJON,
    FORTSATT_MEDLEMSKAP_UNNTAK_FORELDRELOEST_BARN_I_KULL_MEDLEM_TRYGDEN,
    ALDER_BARN,
    ALDER_BARN_UNNTAK_UTDANNING,
    ALDER_BARN_UNNTAK_LAERLING_PRAKTIKANT,
    DOEDSFALL_FORELDER,
    YRKESSKADE_AVDOED
}