package no.nav.etterlatte.rapidsandrivers

object EventNames {
    const val REGULERING_EVENT_NAME = "REGULERING"
    const val GRUNNLAGSVERSJONERING_EVENT_NAME = "GRUNNLAGSVERSJONERING"
    const val VERSJONER_GRUNNLAG_EVENT_NAME = "VERSJONER_GRUNNLAG"
    const val FINN_LOEPENDE_YTELSER = "FINN_LOEPENDE_YTELSER"
    const val OMREGNINGSHENDELSE = "OMREGNINGSHENDELSE"
    const val VILKAARSVURDER = "VILKAARSVURDER"
    const val TRYGDETID = "TRYGDETID"
    const val BEREGN = "BEREGN"
    const val OPPRETT_VEDTAK = "OPPRETT_VEDTAK"
    const val FEILA = "FEILA"
    const val FORDELER_STATISTIKK = "FORDELER:STATISTIKK"
}
