package no.nav.etterlatte.libs.common.vikaar


enum class Kriterietyper {
    AVDOED_ER_FORELDER,
    DOEDSFALL_ER_REGISTRERT_I_PDL,
    SOEKER_ER_UNDER_20_PAA_VIRKNINGSDATO,
    AVDOED_IKKE_OPPHOLD_UTLAND_SISTE_FEM_AAR,
    SOEKER_IKKE_ADRESSE_I_UTLANDET,
    GJENLEVENDE_FORELDER_IKKE_ADRESSE_I_UTLANDET,
    SAMME_BOSTEDSADRESSE,
}