package no.nav.etterlatte.libs.common.vikaar

enum class Vilkaartyper {
    SOEKER_ER_UNDER_20,
    DOEDSFALL_ER_REGISTRERT,
    AVDOEDES_FORUTGAAENDE_MEDLEMSKAP,
    BARNETS_MEDLEMSKAP,

    GJENLEVENDE_OG_BARN_SAMME_BOSTEDADRESSE,
    BARN_BOR_PAA_AVDOEDES_ADRESSE,
    BARN_INGEN_OPPGITT_UTLANDSADRESSE,
    SAKSBEHANDLER_RESULTAT,
    FORMAAL_FOR_YTELSEN
}