package no.nav.etterlatte.libs.common.behandling.opplysningstyper

enum class Opplysningstyper {
    AVDOED_PDL_V1,
    GJENLEVENDE_FORELDER_PDL_V1,
    SOEKER_PDL_V1,

    AVDOED_SOEKNAD_V1,
    SOEKER_SOEKNAD_V1,
    GJENLEVENDE_FORELDER_SOEKNAD_V1,
    INNSENDER_SOEKNAD_V1,

    UTBETALINGSINFORMASJON_V1,
    SOEKNAD_MOTTATT_DATO,
    SAMTYKKE,
    SOEKNADSTYPE_V1
}