package tilgangsstyring

enum class AzureGroup(val envKey: String) {
    ATTESTANT("AZUREAD_ATTESTANT_GROUPID"),
    SAKSBEHANDLER("AZUREAD_SAKSBEHANDLER_GROUPID"),
    STRENGT_FORTROLIG("AZUREAD_STRENGT_FORTROLIG_GROUPID"),
    FORTROLIG("AZUREAD_FORTROLIG_GROUPID"),
    EGEN_ANSATT("AZUREAD_EGEN_ANSATT_GROUPID"),
    NASJONAL_UTEN_LOGG("AZUREAD_NASJONAL_TILGANG_UTEN_LOGG_GROUPID"),
    NASJONAL_MED_LOGG("AZUREAD_NASJONAL_TILGANG_MED_LOGG_GROUPID")
}