package no.nav.etterlatte.tilgangsstyring

import no.nav.etterlatte.libs.common.EnvEnum

enum class AzureGroup(
    val envKey: AzureKey,
) {
    ATTESTANT(AzureKey.AZUREAD_ATTESTANT_GROUPID),
    ATTESTANT_GJENNY(AzureKey.AZUREAD_ATTESTANT_GJENNY_GROUPID),
    SAKSBEHANDLER(AzureKey.AZUREAD_SAKSBEHANDLER_GROUPID),
    STRENGT_FORTROLIG(AzureKey.AZUREAD_STRENGT_FORTROLIG_GROUPID),
    FORTROLIG(AzureKey.AZUREAD_FORTROLIG_GROUPID),
    EGEN_ANSATT(AzureKey.AZUREAD_EGEN_ANSATT_GROUPID),
    NASJONAL_UTEN_LOGG(AzureKey.AZUREAD_NASJONAL_TILGANG_UTEN_LOGG_GROUPID),
    NASJONAL_MED_LOGG(AzureKey.AZUREAD_NASJONAL_TILGANG_MED_LOGG_GROUPID),
}

enum class AzureKey : EnvEnum {
    AZUREAD_ATTESTANT_GROUPID,
    AZUREAD_ATTESTANT_GJENNY_GROUPID,
    AZUREAD_SAKSBEHANDLER_GROUPID,
    AZUREAD_STRENGT_FORTROLIG_GROUPID,
    AZUREAD_FORTROLIG_GROUPID,
    AZUREAD_EGEN_ANSATT_GROUPID,
    AZUREAD_NASJONAL_TILGANG_UTEN_LOGG_GROUPID,
    AZUREAD_NASJONAL_TILGANG_MED_LOGG_GROUPID,
    ;

    override fun name() = name
}
