package no.nav.etterlatte.libs.common.grunnlag.opplysningstyper

enum class Opplysningstyper {
    PERSONGALLERI_V1,
    AVDOED_PDL_V1,
    GJENLEVENDE_FORELDER_PDL_V1,
    SOEKER_PDL_V1,

    AVDOED_SOEKNAD_V1,
    SOEKER_SOEKNAD_V1,
    GJENLEVENDE_FORELDER_SOEKNAD_V1,
    INNSENDER_SOEKNAD_V1,

    UTBETALINGSINFORMASJON_V1,
    SOEKNAD_MOTTATT_DATO,
    SAMTYKKE,
    SOEKNADSTYPE_V1,

    PENSJON_UFORE_V1, // Todo: brukes ikke lenger?
    ARBEIDSFORHOLD_V1,

    AVDOED_INNTEKT_V1,
    SAKSBEHANDLER_AVDOED_MEDLEMSKAPS_PERIODE,

    /* Grunnlag v2 */
    NAVN,
    FOEDSELSNUMMER,
    FOEDSELSDATO,
    FOEDSELSAAR,
    FOEDELAND,
    DOEDSDATO,
    ADRESSEBESKYTTELSE,
    BOSTEDSADRESSE,
    DELTBOSTEDSADRESSE,
    KONTAKTADRESSE,
    OPPHOLDSADRESSE,
    SIVILSTATUS,
    STATSBORGERSKAP,
    UTLAND,
    FAMILIERELASJON,
    AVDOEDESBARN,
    VERGEMAALELLERFREMTIDSFULLMAKT,
    PERSONROLLE,
    UTENLANDSOPPHOLD,
    UTENLANDSADRESSE,
    INNTEKT,
    MEDLEMSKAPSPERIODE,
    KOMMER_BARNET_TILGODE,

    SOESKEN_I_BEREGNINGEN // Kun for soeskenjustering
}