object Ktor2 {
    private const val version = "2.2.2"

    const val OkHttp = "io.ktor:ktor-client-okhttp:$version"
    const val ClientCore = "io.ktor:ktor-client-core:$version"
    const val ClientLoggingJvm = "io.ktor:ktor-client-logging-jvm:$version"
    const val ClientAuth = "io.ktor:ktor-client-auth:$version"
    const val ClientJackson = "io.ktor:ktor-client-jackson:$version"
    const val ClientLogging = "io.ktor:ktor-client-logging:$version"
    const val ClientCioJvm = "io.ktor:ktor-client-cio-jvm:$version"
    const val ServerCore = "io.ktor:ktor-server-core:$version"
    const val ServerCio = "io.ktor:ktor-server-cio:$version"
    const val Auth = "io.ktor:ktor-server-auth:$version"
    const val AuthJwt = "io.ktor:ktor-server-auth-jwt:$version"
    const val ServerContentNegotiation = "io.ktor:ktor-server-content-negotiation:$version"
    const val ClientContentNegotiation = "io.ktor:ktor-client-content-negotiation:$version"
    const val ServerHtmlBuilder = "io.ktor:ktor-server-html-builder:$version"
    const val Jackson = "io.ktor:ktor-serialization-jackson:$version"
    const val CallLogging = "io.ktor:ktor-server-call-logging:$version"
    const val CallId = "io.ktor:ktor-server-call-id:$version"
    const val StatusPages = "io.ktor:ktor-server-status-pages:$version"
    const val MetricsMicrometer = "io.ktor:ktor-server-metrics-micrometer:$version"
    const val Mustache = "io.ktor:ktor-server-mustache:$version"

    const val ClientMock = "io.ktor:ktor-client-mock:$version"
    const val ServerTests = "io.ktor:ktor-server-tests:$version"
}