package no.nav.etterlatte.brev

interface Brevbakerkode

/*
Denne enumen brukes primært for kommunikasjonen mot brevbakeren.

Denne enumen henger tett sammen med Brevkoder-enumen.
Vurdér om du heller bør bruke den, hvis du er utenfor rein brevbaker-kontekst.
 */
enum class EtterlatteBrevKode : Brevbakerkode {
    BP_AVSLAG,
    BP_AVSLAG_UTFALL,
    BP_INNVILGELSE,
    BP_INNVILGELSE_UTFALL,
    BP_INNVILGELSE_FORELDRELOES,
    BP_INNVILGELSE_UTFALL_FORELDRELOES,
    BP_OPPHOER,
    BP_OPPHOER_UTFALL,
    BP_REVURDERING,
    BP_REVURDERING_UTFALL,
    BARNEPENSJON_FORHAANDSVARSEL_OMREGNING,
    BP_VARSEL,
    BP_VARSEL_UTFALL,
    BP_VEDTAK_OMREGNING,
    BP_VEDTAK_OMREGNING_FERDIG,
    BP_INFORMASJON_DOEDSFALL,
    BP_DOEDSFALL_18_20_VED_REFORMTIDSPUNKT,
    BP_INFORMASJON_MOTTATT_SOEKNAD,
    BP_INFORMASJON_INNHENTING_AV_OPPLYSNINGER,

    OMS_INFORMASJON_DOEDSFALL,
    OMS_INFORMASJON_MOTTATT_SOEKNAD,
    OMS_INFORMASJON_INNHENTING_AV_OPPLYSNINGER,
    OMS_AVSLAG,
    OMS_AVSLAG_UTFALL,
    OMS_INNVILGELSE,
    OMS_INNVILGELSE_UTFALL,
    OMS_OPPHOER,
    OMS_OPPHOER_UTFALL,
    OMS_REVURDERING,
    OMS_REVURDERING_UTFALL,
    OMS_VARSEL,
    OMS_VARSEL_UTFALL,
    OMS_VARSEL_AKTIVITETSPLIKT,
    OMS_VARSEL_AKTIVITETSPLIKT_UTFALL,
    OMS_AKTIVITETSPLIKT_INFORMASJON_4MND_INNHOLD,
    OMS_AKTIVITETSPLIKT_INFORMASJON_10MND_INNHOLD,
    OMS_AKTIVITETSPLIKT_INFORMASJON_6MND_INNHOLD,
    OMSTILLINGSSTOENAD_INNTEKTSJUSTERING_VARSEL,
    OMS_INNTEKTSJUSTERING_VEDTAK,
    OMS_INNTEKTSJUSTERING_VEDTAK_UTFALL,

    TILBAKEKREVING_INNHOLD,
    TILBAKEKREVING_FERDIG,

    AVVIST_KLAGE_INNHOLD,
    AVVIST_KLAGE_FERDIG,
    KLAGE_SAKSBEHANDLINGS_INFO,
    TOM_DELMAL,
    TOM_MAL_INFORMASJONSBREV,
    UTSATT_KLAGEFRIST,

    KLAGE_OVERSENDELSE_BRUKER,
    KLAGE_OVERSENDELSE_BLANKETT,

    OPPLASTET_PDF,
    INGEN_REDIGERBAR_DEL,
}

enum class Brevtype {
    VEDTAK,
    VARSEL,
    INFORMASJON,
    OPPLASTET_PDF,
    MANUELT,
    VEDLEGG,
    NOTAT,
    OVERSENDELSE_KLAGE,
    SLETTET_VARSEL,
    INGEN, // Til bruk for å modellere at brevet ikke har en redigerbar del
    ;

    fun erKobletTilEnBehandling(): Boolean = this in listOf(VEDTAK, VARSEL, VEDLEGG)
}

enum class Vedlegg(
    val tittel: String,
) : Brevbakerkode {
    BARNEPENSJON_VEDLEGG_BEREGNING_TRYGDETID_UTFALL("Trygdetid i vedlegg beregning av barnepensjon"),
    BARNEPENSJON_VEDLEGG_FORHAANDSVARSEL_UTFALL("Utfall ved forhåndsvarsel av feilutbetaling"),
    OMSTILLINGSSTOENAD_VEDLEGG_BEREGNING_UTFALL("Utfall ved beregning av omstillingsstønad"),
    OMSTILLINGSSTOENAD_VEDLEGG_FORHAANDSVARSEL_UTFALL("Utfall ved forhåndsvarsel av feilutbetaling"),
}
