no.nav.security.jwt {
  issuers = [
      {
         issuer_name = azure
         discoveryurl = ${?AZURE_APP_WELL_KNOWN_URL}
         accepted_audience = ${?AZURE_APP_CLIENT_ID}
      }
  ]
}

azure.app.client.id = ${AZURE_APP_CLIENT_ID}
azure.app.client.secret = ${AZURE_APP_CLIENT_SECRET}
azure.app.well.known.url = ${AZURE_APP_WELL_KNOWN_URL}


dolly.client.id = ${DOLLY_CLIENT_ID}
dolly.resource.url = ${DOLLY_RESOURCE_URL}

testnav.client.id = ${TESTNAV_CLIENT_ID}
testnav.resource.url = ${TESTNAV_RESOURCE_URL}

behandling.resource.url = ${ETTERLATTE_BEHANDLING_URL}

# Prosessering-admin-API ligger i etterlatte-behandling-appen (ikke vedtaksvurdering som over)
behandling.app.url = ${ETTERLATTE_BEHANDLING_APP_URL}
behandling.app.scope = ${ETTERLATTE_BEHANDLING_APP_SCOPE}
