#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

changedFrontendFiles=$(git diff --name-only --cached | grep '\.\(ts\|js\)[x"]\?$' || true)

if [ -n "${changedFrontendFiles-unset}" ]; then
  echo "🛠 Running lint-staged"

  cd ./apps/etterlatte-saksbehandling-ui
  yarn lint-staged
  cd ../../ # Tilbake til prosjektrot

  echo "✍️ Linted frontend files *.{js,ts,tsx}"
fi


changedKotlinFiles=$(git diff --name-only --cached | grep '\.kt[s"]\?$' || true)

if [ -n "${changedKotlinFiles-unset}" ]; then
    echo "🛠 Running ktlint"

    #store the result of the commit in a variable and split into array items with newline
    committedFiles=$(git diff --name-only --cached --diff-filter=d | grep '\.kt[s"]\?$')
    files=$(echo $committedFiles | tr ";" "\\n")

    # https://github.com/pinterest/ktlint pre-commit hook
    git diff --name-only --cached | grep '\.kt[s"]\?$' | xargs ktlint -F
    echo "✍️ Formatted kotlin files"

    #replay items in the commits array and add only those files
    for file in $files
    do
        git add $file
    done
fi

echo "🏆 Files staged"

exit 0