#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

cd ./apps/etterlatte-saksbehandling-ui && yarn lint-staged

echo "Running ktlint..."

#store the result of the commit in a variable and split into array items with newline
cd ../../
committedFiles=$(git diff --name-only --cached)
files=$(echo $committedFiles | tr ";" "\\n")

ktlint -F '**/*.kt' '!/**/build/*'

#replay items in the commits array and add only those files
for file in $files
do
    git add $file
done

exit 0

echo "Running ktlint check..."
