name: .deploy-main.yaml

on:
  workflow_call:
    inputs:
      applikasjon:
        description: 'Navnet på applikasjonen'
        required: true
        type: string

env:
  image: europe-north1-docker.pkg.dev/nais-management-233d/etterlatte/pensjon-etterlatte-saksbehandling-etterlatte-${{ inputs.applikasjon }}:main

jobs:
  deploy-main:
    name: deploy-main
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6.0.2
      - uses: nais/deploy/actions/deploy@fa754451577294aae42872a69b888b3470478ec1 # ratchet:nais/deploy/actions/deploy@v2
        env:
          TELEMETRY: ${{ steps.docker-build-push.outputs.telemetry }}
          CLUSTER: dev-gcp
          RESOURCE: apps/etterlatte-${{ inputs.applikasjon }}/.nais/dev.yaml
          VAR: image=${{ env.image }}
