name: Deploy alerts to NAIS
on:
  push:
    branches:
      - main
    paths:
      - 'alerts.yaml'
      - '.github/workflows/alerts.yaml'

permissions:
  contents: read
  id-token: write

jobs:
  apply-alerts:
    name: Apply alerts to cluster
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # ratchet:actions/checkout@v5
      - name: deploy to dev
        uses: nais/deploy/actions/deploy@fa754451577294aae42872a69b888b3470478ec1 # ratchet:nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: alerts.yaml
          VAR: LOGS_URL=https://logs.az.nav.no/goto/e50de3b91964f2cc53e69aa07a48e96e?security_tenant=navlogs
      - name: deploy to prod
        uses: nais/deploy/actions/deploy@fa754451577294aae42872a69b888b3470478ec1 # ratchet:nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: alerts.yaml
          VAR: LOGS_URL=https://logs.az.nav.no/goto/7ce0886fddc960bdc9d19d0071e6f8f0?security_tenant=navlogs
